<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 (APPENDIX) In-Class Review Questions | STAT 423 Review Guide</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="5 (APPENDIX) In-Class Review Questions | STAT 423 Review Guide" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="shaandro/stat-423" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 (APPENDIX) In-Class Review Questions | STAT 423 Review Guide" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="Shaandro Sarkar" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="independent-k-sample-tests.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STAT 423 Review Guide</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About</a></li>
<li class="chapter" data-level="2" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html"><i class="fa fa-check"></i><b>2</b> Paired Two-Sample Tests</a><ul>
<li class="chapter" data-level="2.1" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html#paired-t-test"><i class="fa fa-check"></i><b>2.1</b> Paired <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="2.2" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html#sign-test"><i class="fa fa-check"></i><b>2.2</b> Sign test</a></li>
<li class="chapter" data-level="2.3" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html#wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>2.3</b> Wilcoxon Signed-Rank Test</a></li>
<li class="chapter" data-level="2.4" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html#permutation-test"><i class="fa fa-check"></i><b>2.4</b> Permutation Test</a><ul>
<li class="chapter" data-level="2.4.1" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html#exact-permutation-test"><i class="fa fa-check"></i><b>2.4.1</b> Exact permutation test</a></li>
<li class="chapter" data-level="2.4.2" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html#large-sample-approximation-for-permutation-test"><i class="fa fa-check"></i><b>2.4.2</b> Large-sample approximation for permutation test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html"><i class="fa fa-check"></i><b>3</b> Independent Two-Sample Tests</a><ul>
<li class="chapter" data-level="3.1" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#two-sample-t-test"><i class="fa fa-check"></i><b>3.1</b> Two-Sample <span class="math inline">\(t\)</span>-Test</a></li>
<li class="chapter" data-level="3.2" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#permutation-test-1"><i class="fa fa-check"></i><b>3.2</b> Permutation Test</a><ul>
<li class="chapter" data-level="3.2.1" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#exact-permutation-test-1"><i class="fa fa-check"></i><b>3.2.1</b> Exact permutation test</a></li>
<li class="chapter" data-level="3.2.2" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#large-sample-approximation-for-permutation-test-1"><i class="fa fa-check"></i><b>3.2.2</b> Large-sample approximation for permutation test</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#mann-whitney-test"><i class="fa fa-check"></i><b>3.3</b> Mann-Whitney Test</a></li>
<li class="chapter" data-level="3.4" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#kolmogorov-smirnov-test"><i class="fa fa-check"></i><b>3.4</b> Kolmogorov-Smirnov Test</a></li>
<li class="chapter" data-level="3.5" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#tests-on-deviances"><i class="fa fa-check"></i><b>3.5</b> Tests on Deviances</a><ul>
<li class="chapter" data-level="3.5.1" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#f-test"><i class="fa fa-check"></i><b>3.5.1</b> <span class="math inline">\(F\)</span>-Test</a></li>
<li class="chapter" data-level="3.5.2" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#nonparametric-test"><i class="fa fa-check"></i><b>3.5.2</b> Nonparametric Test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html"><i class="fa fa-check"></i><b>4</b> Independent <span class="math inline">\(K\)</span>-Sample Tests</a><ul>
<li class="chapter" data-level="4.1" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#classic-f-test"><i class="fa fa-check"></i><b>4.1</b> Classic <span class="math inline">\(F\)</span>-Test</a></li>
<li class="chapter" data-level="4.2" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#permutation-f-test"><i class="fa fa-check"></i><b>4.2</b> Permutation <span class="math inline">\(F\)</span>-Test</a></li>
<li class="chapter" data-level="4.3" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#kruskal-walis-test"><i class="fa fa-check"></i><b>4.3</b> Kruskal-Walis Test</a></li>
<li class="chapter" data-level="4.4" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#jonkheere-terpstra-test"><i class="fa fa-check"></i><b>4.4</b> Jonkheere-Terpstra Test</a></li>
<li class="chapter" data-level="4.5" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#multiple-comparisons-and-multiple-testing"><i class="fa fa-check"></i><b>4.5</b> Multiple Comparisons and Multiple Testing</a><ul>
<li class="chapter" data-level="4.5.1" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#multiple-comparisons"><i class="fa fa-check"></i><b>4.5.1</b> Multiple Comparisons</a></li>
<li class="chapter" data-level="4.5.2" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#multiple-testing"><i class="fa fa-check"></i><b>4.5.2</b> Multiple Testing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="appendix-in-class-review-questions.html"><a href="appendix-in-class-review-questions.html"><i class="fa fa-check"></i><b>5</b> (APPENDIX) In-Class Review Questions</a><ul>
<li class="chapter" data-level="5.1" data-path="appendix-in-class-review-questions.html"><a href="appendix-in-class-review-questions.html#question-1-estimator"><i class="fa fa-check"></i><b>5.1</b> Question 1: Estimator</a></li>
<li class="chapter" data-level="5.2" data-path="appendix-in-class-review-questions.html"><a href="appendix-in-class-review-questions.html#question-2-one-proportion-z-test"><i class="fa fa-check"></i><b>5.2</b> Question 2: One-Proportion <span class="math inline">\(z\)</span>-Test</a></li>
<li class="chapter" data-level="5.3" data-path="appendix-in-class-review-questions.html"><a href="appendix-in-class-review-questions.html#question-3-paired-two-sample-tests"><i class="fa fa-check"></i><b>5.3</b> Question 3: Paired Two-Sample Tests</a></li>
<li class="chapter" data-level="5.4" data-path="appendix-in-class-review-questions.html"><a href="appendix-in-class-review-questions.html#question-4-paired-permutation-test"><i class="fa fa-check"></i><b>5.4</b> Question 4: Paired Permutation Test</a></li>
<li class="chapter" data-level="5.5" data-path="appendix-in-class-review-questions.html"><a href="appendix-in-class-review-questions.html#question-5-anova-and-classic-f-test"><i class="fa fa-check"></i><b>5.5</b> Question 5: ANOVA and Classic <span class="math inline">\(F\)</span>-Test</a></li>
<li class="chapter" data-level="5.6" data-path="appendix-in-class-review-questions.html"><a href="appendix-in-class-review-questions.html#question-6-kruskal-wallis-test"><i class="fa fa-check"></i><b>5.6</b> Question 6: Kruskal-Wallis Test</a></li>
<li class="chapter" data-level="5.7" data-path="appendix-in-class-review-questions.html"><a href="appendix-in-class-review-questions.html#question-7-sse-from-anova"><i class="fa fa-check"></i><b>5.7</b> Question 7: SSE (from ANOVA)</a></li>
<li class="chapter" data-level="5.8" data-path="appendix-in-class-review-questions.html"><a href="appendix-in-class-review-questions.html#question-8-sstr-from-anova"><i class="fa fa-check"></i><b>5.8</b> Question 8: SSTr (from ANOVA)</a></li>
<li class="chapter" data-level="5.9" data-path="appendix-in-class-review-questions.html"><a href="appendix-in-class-review-questions.html#question-9-permutation-f-test"><i class="fa fa-check"></i><b>5.9</b> Question 9: Permutation <span class="math inline">\(F\)</span>-test</a></li>
<li class="chapter" data-level="5.10" data-path="appendix-in-class-review-questions.html"><a href="appendix-in-class-review-questions.html#question-10-multiple-comparison-pairwise-t-tests"><i class="fa fa-check"></i><b>5.10</b> Question 10: Multiple Comparison (Pairwise <span class="math inline">\(t\)</span>-Tests)</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STAT 423 Review Guide</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="appendix-in-class-review-questions" class="section level1">
<h1><span class="header-section-number">5</span> (APPENDIX) In-Class Review Questions</h1>
<div id="question-1-estimator" class="section level2">
<h2><span class="header-section-number">5.1</span> Question 1: Estimator</h2>
<p>Amazon recommends customers products according to their purchasing history.
Among 10,000 independent recommendations, 118 were accepted.
The estimator of acceptance rate is <span class="math inline">\(\hat{p} = 118/10000\)</span>.</p>
</div>
<div id="question-2-one-proportion-z-test" class="section level2">
<h2><span class="header-section-number">5.2</span> Question 2: One-Proportion <span class="math inline">\(z\)</span>-Test</h2>
<p>Let <span class="math inline">\(p\)</span> be the true acceptance rate.
Test the hypotheses
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(p = 0.02\)</span> vs <span class="math inline">\(H_a\)</span>: <span class="math inline">\(p &lt; 0.02.\)</span></p>
<p>To find the <span class="math inline">\(p\)</span>-value for this test,
we will use the one-proportion <span class="math inline">\(z\)</span>-test
statistic<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>
<span class="math display">\[Z = \frac{n\hat{p} - np_0}{\sqrt{np_0(1 - p_0)}}.\]</span></p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1">S &lt;-<span class="st"> </span><span class="dv">118</span> <span class="co"># number of successes</span></a>
<a class="sourceLine" id="cb60-2" title="2">n &lt;-<span class="st"> </span><span class="dv">10000</span> <span class="co"># sample size</span></a>
<a class="sourceLine" id="cb60-3" title="3">p0 &lt;-<span class="st"> </span><span class="fl">0.02</span> <span class="co"># expected probability</span></a>
<a class="sourceLine" id="cb60-4" title="4">ES &lt;-<span class="st"> </span>n<span class="op">*</span>p0 <span class="co"># expected number of successes</span></a>
<a class="sourceLine" id="cb60-5" title="5">VarS &lt;-<span class="st"> </span>n<span class="op">*</span>p0<span class="op">*</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>p0) <span class="co"># variance</span></a>
<a class="sourceLine" id="cb60-6" title="6">Z &lt;-<span class="st"> </span>(S <span class="op">-</span><span class="st"> </span>ES) <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(VarS) <span class="co"># test statistic</span></a>
<a class="sourceLine" id="cb60-7" title="7"><span class="kw">pnorm</span>(Z) <span class="co"># p-value</span></a></code></pre></div>
<pre><code>## [1] 2.35449e-09</code></pre>
<p>Under large-sample approximation, the <span class="math inline">\(p\)</span>-value of this test is
<span class="math inline">\(2.35449 \times 10^{-9}\)</span>.</p>
</div>
<div id="question-3-paired-two-sample-tests" class="section level2">
<h2><span class="header-section-number">5.3</span> Question 3: Paired Two-Sample Tests</h2>
<p>Load the R dataset
<code>sleep</code><a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1"><span class="kw">data</span>(<span class="st">&quot;sleep&quot;</span>)</a>
<a class="sourceLine" id="cb62-2" title="2"><span class="kw">head</span>(sleep)</a></code></pre></div>
<pre><code>##   extra group ID
## 1   0.7     1  1
## 2  -1.6     1  2
## 3  -0.2     1  3
## 4  -1.2     1  4
## 5  -0.1     1  5
## 6   3.4     1  6</code></pre>
<p>Test <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1 = \mu_2\)</span> vs <span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu_1 &lt; \mu_2\)</span>,
where <span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span> are the centers of the two groups.
Which method gives the smaller <span class="math inline">\(p\)</span>-value:
<span class="math inline">\(t\)</span>-test or Wilcoxon signed-rank test?</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1"><span class="co"># paired t-test p-value</span></a>
<a class="sourceLine" id="cb64-2" title="2"><span class="kw">t.test</span>(extra <span class="op">~</span><span class="st"> </span>group, <span class="dt">paired =</span> <span class="ot">TRUE</span>, <span class="dt">data =</span> sleep, <span class="dt">alternative =</span> <span class="st">&quot;less&quot;</span>)<span class="op">$</span>p.value</a></code></pre></div>
<pre><code>## [1] 0.001416445</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" title="1"><span class="co"># paired Wilcoxon test p-value</span></a>
<a class="sourceLine" id="cb66-2" title="2"><span class="kw">wilcox.test</span>(extra <span class="op">~</span><span class="st"> </span>group, <span class="dt">paired =</span> <span class="ot">TRUE</span>, <span class="dt">data =</span> sleep, <span class="dt">alternative =</span> <span class="st">&quot;less&quot;</span>)<span class="op">$</span>p.value</a></code></pre></div>
<pre><code>## Warning in wilcox.test.default(x = c(0.7, -1.6, -0.2, -1.2, -0.1, 3.4, 3.7, :
## cannot compute exact p-value with ties</code></pre>
<pre><code>## Warning in wilcox.test.default(x = c(0.7, -1.6, -0.2, -1.2, -0.1, 3.4, 3.7, :
## cannot compute exact p-value with zeroes</code></pre>
<pre><code>## [1] 0.004545349</code></pre>
<p>Since <span class="math inline">\(0.0014 &lt; 0.0045\)</span>, the <span class="math inline">\(t\)</span>-test has a smaller <span class="math inline">\(p\)</span>-value than the Wilcoxon test.</p>
<p>We now consider the permutation test.
The expression that generates the appropriate permutation outcome is</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1">z &lt;-<span class="st"> </span><span class="kw">abs</span>(sleep<span class="op">$</span>extra[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>] <span class="op">-</span><span class="st"> </span>sleep<span class="op">$</span>extra[<span class="dv">11</span><span class="op">:</span><span class="dv">20</span>])</a>
<a class="sourceLine" id="cb70-2" title="2"><span class="kw">sample</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>), <span class="dv">10</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>) <span class="op">*</span><span class="st"> </span>z</a></code></pre></div>
<pre><code>##  [1] -1.2  2.4 -1.3 -1.3  0.0  1.0  1.8  0.8  4.6  1.4</code></pre>
</div>
<div id="question-4-paired-permutation-test" class="section level2">
<h2><span class="header-section-number">5.4</span> Question 4: Paired Permutation Test</h2>
<p>Load the R dataset <code>sleep</code>.
Test <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1 = \mu_2\)</span> vs <span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu_1 \neq \mu_2\)</span>,
where <span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span> are the centers of the two groups.</p>
<p>Consider the permutation test. What is the total number of permutation outcomes?</p>
<p>The <code>sleep</code> dataset has 10 paired observations.
If <span class="math inline">\(n\)</span> is the sample size, then the number of permutation outcomes is <span class="math inline">\(2^n\)</span>.
For the <code>sleep</code> dataset,
the number of permutation outcomes is thus <span class="math inline">\(2^{10} = 1024\)</span>.</p>
</div>
<div id="question-5-anova-and-classic-f-test" class="section level2">
<h2><span class="header-section-number">5.5</span> Question 5: ANOVA and Classic <span class="math inline">\(F\)</span>-Test</h2>
<p>Load the R dataset <code>iris</code>.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1"><span class="kw">data</span>(<span class="st">&quot;iris&quot;</span>)</a>
<a class="sourceLine" id="cb72-2" title="2"><span class="kw">head</span>(iris)</a></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<p>For the first column, consider the hypothesis
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1 = \mu_2 = \mu_3\)</span> vs <span class="math inline">\(H_a\)</span>: <span class="math inline">\(H_0\)</span> is not true,
where <span class="math inline">\(\mu_1\)</span>, <span class="math inline">\(\mu_2\)</span>, and <span class="math inline">\(\mu_3\)</span>
are the centers for the sepal lengths of
<em>Iris setosa</em>, <em>versicolor</em>, and <em>virginica</em>, respectively.</p>
<p>We will find the <span class="math inline">\(p\)</span>-value of the <span class="math inline">\(F\)</span>-test for these hypotheses
by generating an <code>anova</code> table from the <code>lm</code> model.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" title="1"><span class="kw">anova</span>(<span class="kw">lm</span>(Sepal.Length <span class="op">~</span><span class="st"> </span>Species, <span class="dt">data =</span> iris))</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Sepal.Length
##            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## Species     2 63.212  31.606  119.26 &lt; 2.2e-16 ***
## Residuals 147 38.956   0.265                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>From the ANOVA table, we have <span class="math inline">\(p\text{-value} &lt; 2.2 \times 10^{-16}\)</span>.</p>
</div>
<div id="question-6-kruskal-wallis-test" class="section level2">
<h2><span class="header-section-number">5.6</span> Question 6: Kruskal-Wallis Test</h2>
<p>Load the R dataset <code>iris</code>.
For the first column, consider the hypothesis
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1 = \mu_2 = \mu_3\)</span> vs <span class="math inline">\(H_a\)</span>: <span class="math inline">\(H_0\)</span> is not true,
where <span class="math inline">\(\mu_1\)</span>, <span class="math inline">\(\mu_2\)</span>, and <span class="math inline">\(\mu_3\)</span>
are the centers for the sepal lengths of
<em>Iris setosa</em>, <em>versicolor</em>, and <em>virginica</em>, respectively.</p>
<p>We will find the <span class="math inline">\(p\)</span>-value of the Kruskal-Wallis test
using <code>kruskal.test</code>.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" title="1"><span class="kw">kruskal.test</span>(iris<span class="op">$</span>Sepal.Length, iris<span class="op">$</span>Species)</a></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  iris$Sepal.Length and iris$Species
## Kruskal-Wallis chi-squared = 96.937, df = 2, p-value &lt; 2.2e-16</code></pre>
<p>Thus <span class="math inline">\(p\text{-value} &lt; 2.2 \times 10^{-16}\)</span>.</p>
</div>
<div id="question-7-sse-from-anova" class="section level2">
<h2><span class="header-section-number">5.7</span> Question 7: SSE (from ANOVA)</h2>
<p>Load the R dataset <code>iris</code>.
Consider the first numerical column and find the SSE.</p>
<p>The SSE can be found on the ANOVA table,
which we already generated in Question 5.
The SSE is the value in the row <code>Residuals</code> and the column <code>Sum Sq</code>,
i.e. <span class="math inline">\(\mathrm{SSE} = 38.956\)</span>.</p>
</div>
<div id="question-8-sstr-from-anova" class="section level2">
<h2><span class="header-section-number">5.8</span> Question 8: SSTr (from ANOVA)</h2>
<p>Load the R dataset <code>iris</code>.
Consider the first numerical column and find the SSTr.</p>
<p>The SSTr can also be found on the ANOVA table.
The SSTr is the value in the row <code>Species</code> and the column <code>Sum Sq</code>,
i.e. <span class="math inline">\(\mathrm{SSTr} = 63.212\)</span>.</p>
</div>
<div id="question-9-permutation-f-test" class="section level2">
<h2><span class="header-section-number">5.9</span> Question 9: Permutation <span class="math inline">\(F\)</span>-test</h2>
<p>Load the R dataset <code>iris</code>.
For the first column, compute the <span class="math inline">\(p\)</span>-value using the permutation <span class="math inline">\(F\)</span>-test for
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_1 = \mu_2 = \mu_3\)</span> vs <span class="math inline">\(H_a\)</span>: <span class="math inline">\(H_0\)</span> is not true.</p>
<p>We will perform the permutation test using <span class="math inline">\(R = 5000\)</span> permutation samples.
We use the simplified calculation of the <span class="math inline">\(F\)</span>-statistic<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></p>
<p><span class="math display">\[F \propto \sum_{i=1}^K n_i \bar{X}_i ^2,\]</span>
where <span class="math inline">\(K\)</span> is the number of groups,
<span class="math inline">\(n_i\)</span> is the number of observations in group <span class="math inline">\(i\)</span>,
and <span class="math inline">\(\bar{X}_i\)</span> is the mean of group <span class="math inline">\(i\)</span>.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" title="1"><span class="co"># number of samples in each group</span></a>
<a class="sourceLine" id="cb78-2" title="2">n &lt;-<span class="st"> </span><span class="kw">tapply</span>(iris<span class="op">$</span>Sepal.Length, iris<span class="op">$</span>Species, length)</a>
<a class="sourceLine" id="cb78-3" title="3"><span class="co"># total number of observations</span></a>
<a class="sourceLine" id="cb78-4" title="4">N &lt;-<span class="st"> </span><span class="kw">sum</span>(n)</a>
<a class="sourceLine" id="cb78-5" title="5"><span class="co"># sepal length of each observation</span></a>
<a class="sourceLine" id="cb78-6" title="6">y &lt;-<span class="st"> </span>iris<span class="op">$</span>Sepal.Length</a>
<a class="sourceLine" id="cb78-7" title="7"><span class="co"># species of each observation</span></a>
<a class="sourceLine" id="cb78-8" title="8">t &lt;-<span class="st"> </span>iris<span class="op">$</span>Species</a>
<a class="sourceLine" id="cb78-9" title="9"></a>
<a class="sourceLine" id="cb78-10" title="10"><span class="co"># F-statistic</span></a>
<a class="sourceLine" id="cb78-11" title="11">Fobs &lt;-<span class="st"> </span><span class="kw">sum</span>(n <span class="op">*</span><span class="st"> </span><span class="kw">tapply</span>(y, t, mean)<span class="op">^</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb78-12" title="12"></a>
<a class="sourceLine" id="cb78-13" title="13"><span class="co"># number of permutation samples</span></a>
<a class="sourceLine" id="cb78-14" title="14">R &lt;-<span class="st"> </span><span class="dv">5000</span> </a>
<a class="sourceLine" id="cb78-15" title="15"><span class="co"># empty vector for the F-statistic of each permutation sample</span></a>
<a class="sourceLine" id="cb78-16" title="16">F &lt;-<span class="st"> </span><span class="kw">c</span>()</a>
<a class="sourceLine" id="cb78-17" title="17"><span class="co"># calculate permutation sample F-statistics</span></a>
<a class="sourceLine" id="cb78-18" title="18"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>R) {</a>
<a class="sourceLine" id="cb78-19" title="19">  F &lt;-<span class="st"> </span><span class="kw">c</span>(F, <span class="kw">sum</span>(n <span class="op">*</span><span class="st"> </span><span class="kw">tapply</span>(y, <span class="kw">sample</span>(t), mean)<span class="op">^</span><span class="dv">2</span>))</a>
<a class="sourceLine" id="cb78-20" title="20">}</a>
<a class="sourceLine" id="cb78-21" title="21"></a>
<a class="sourceLine" id="cb78-22" title="22"><span class="co"># p-value = proportion of permutation F-statistics greater than Fobs</span></a>
<a class="sourceLine" id="cb78-23" title="23"><span class="kw">mean</span>(Fobs <span class="op">&lt;=</span><span class="st"> </span>F)</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Thus the <span class="math inline">\(p\)</span>-value for the permutation <span class="math inline">\(F\)</span>-test is 0.</p>
</div>
<div id="question-10-multiple-comparison-pairwise-t-tests" class="section level2">
<h2><span class="header-section-number">5.10</span> Question 10: Multiple Comparison (Pairwise <span class="math inline">\(t\)</span>-Tests)</h2>
<p>Load the R dataset <code>iris</code>.
For the first column, compute the <span class="math inline">\(p\)</span>-values from the multiple comparison based on
pairwise <span class="math inline">\(t\)</span>-tests.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" title="1"><span class="kw">pairwise.t.test</span>(y, t)</a></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  y and t 
## 
##            setosa  versicolor
## versicolor 1.8e-15 -         
## virginica  &lt; 2e-16 2.8e-09   
## 
## P value adjustment method: holm</code></pre>
<p>The pair with the smallest <span class="math inline">\(p\)</span>-value is <em>I. setosa</em> vs. <em>I. virginica</em>.</p>

</div>
</div>
















<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>We can use the <span class="math inline">\(z\)</span>-test because <span class="math inline">\(np_0 = 10000(0.02) = 200 &gt; 10\)</span>
and <span class="math inline">\(n(1 - p_0) = 10000(0.98) = 9800 &gt; 10\)</span>.
Dr. Su refers to this as a large-sample approximation because, with a large enough sample,
we can assume that the data is distributed normally.<a href="appendix-in-class-review-questions.html#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>The <code>sleep</code> data shows the effect of two drugs on 10 patients.
The dataset has three columns:
<code>extra</code> (increase in hours of sleep),
<code>group</code> (drug given), and
<code>ID</code> (patient ID).
The data is paired, since each patient was given both drug 1 and drug 2.<a href="appendix-in-class-review-questions.html#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p><code>k-sample.pdf</code>, slide 9<a href="appendix-in-class-review-questions.html#fnref3" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="independent-k-sample-tests.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/shaandro/stat-423/edit/main/class-review.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
