<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1 Paired Two-Sample Tests | STAT 423 Review Guide</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="1 Paired Two-Sample Tests | STAT 423 Review Guide" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="shaandro/stat-423" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1 Paired Two-Sample Tests | STAT 423 Review Guide" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="Shaandro Sarkar" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="independent-two-sample-tests.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STAT 423 Review Guide</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="chapter" data-level="1" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html"><i class="fa fa-check"></i><b>1</b> Paired Two-Sample Tests</a><ul>
<li class="chapter" data-level="1.1" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html#paired-t-test"><i class="fa fa-check"></i><b>1.1</b> Paired <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="1.2" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html#sign-test"><i class="fa fa-check"></i><b>1.2</b> Sign test</a></li>
<li class="chapter" data-level="1.3" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html#wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>1.3</b> Wilcoxon Signed-Rank Test</a></li>
<li class="chapter" data-level="1.4" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html#permutation-test"><i class="fa fa-check"></i><b>1.4</b> Permutation Test</a><ul>
<li class="chapter" data-level="1.4.1" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html#exact-permutation-test"><i class="fa fa-check"></i><b>1.4.1</b> Exact permutation test</a></li>
<li class="chapter" data-level="1.4.2" data-path="paired-two-sample-tests.html"><a href="paired-two-sample-tests.html#large-sample-approximation-for-permutation-test"><i class="fa fa-check"></i><b>1.4.2</b> Large-sample approximation for permutation test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html"><i class="fa fa-check"></i><b>2</b> Independent Two-Sample Tests</a><ul>
<li class="chapter" data-level="2.1" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#two-sample-t-test"><i class="fa fa-check"></i><b>2.1</b> Two-Sample <span class="math inline">\(t\)</span>-Test</a></li>
<li class="chapter" data-level="2.2" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#permutation-test-1"><i class="fa fa-check"></i><b>2.2</b> Permutation Test</a><ul>
<li class="chapter" data-level="2.2.1" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#exact-permutation-test-1"><i class="fa fa-check"></i><b>2.2.1</b> Exact permutation test</a></li>
<li class="chapter" data-level="2.2.2" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#large-sample-approximation-for-permutation-test-1"><i class="fa fa-check"></i><b>2.2.2</b> Large-sample approximation for permutation test</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#mann-whitney-test"><i class="fa fa-check"></i><b>2.3</b> Mann-Whitney Test</a></li>
<li class="chapter" data-level="2.4" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#kolmogorov-smirnov-test"><i class="fa fa-check"></i><b>2.4</b> Kolmogorov-Smirnov Test</a></li>
<li class="chapter" data-level="2.5" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#tests-on-deviances"><i class="fa fa-check"></i><b>2.5</b> Tests on Deviances</a><ul>
<li class="chapter" data-level="2.5.1" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#f-test"><i class="fa fa-check"></i><b>2.5.1</b> <span class="math inline">\(F\)</span>-Test</a></li>
<li class="chapter" data-level="2.5.2" data-path="independent-two-sample-tests.html"><a href="independent-two-sample-tests.html#nonparametric-test"><i class="fa fa-check"></i><b>2.5.2</b> Nonparametric Test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html"><i class="fa fa-check"></i><b>3</b> Independent <span class="math inline">\(K\)</span>-Sample Tests</a><ul>
<li class="chapter" data-level="3.1" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#classic-f-test"><i class="fa fa-check"></i><b>3.1</b> Classic <span class="math inline">\(F\)</span>-Test</a></li>
<li class="chapter" data-level="3.2" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#permutation-f-test"><i class="fa fa-check"></i><b>3.2</b> Permutation <span class="math inline">\(F\)</span>-Test</a></li>
<li class="chapter" data-level="3.3" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#kruskal-walis-test"><i class="fa fa-check"></i><b>3.3</b> Kruskal-Walis Test</a></li>
<li class="chapter" data-level="3.4" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#jonkheere-terpstra-test"><i class="fa fa-check"></i><b>3.4</b> Jonkheere-Terpstra Test</a></li>
<li class="chapter" data-level="3.5" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#multiple-comparisons-and-multiple-testing"><i class="fa fa-check"></i><b>3.5</b> Multiple Comparisons and Multiple Testing</a><ul>
<li class="chapter" data-level="3.5.1" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#multiple-comparisons"><i class="fa fa-check"></i><b>3.5.1</b> Multiple Comparisons</a></li>
<li class="chapter" data-level="3.5.2" data-path="independent-k-sample-tests.html"><a href="independent-k-sample-tests.html#multiple-testing"><i class="fa fa-check"></i><b>3.5.2</b> Multiple Testing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="in-class-review-questions.html"><a href="in-class-review-questions.html"><i class="fa fa-check"></i><b>4</b> In-Class Review Questions</a><ul>
<li class="chapter" data-level="4.1" data-path="in-class-review-questions.html"><a href="in-class-review-questions.html#estimator"><i class="fa fa-check"></i><b>4.1</b> Estimator</a></li>
<li class="chapter" data-level="4.2" data-path="in-class-review-questions.html"><a href="in-class-review-questions.html#one-proportion-z-test"><i class="fa fa-check"></i><b>4.2</b> One-Proportion <span class="math inline">\(z\)</span>-Test</a></li>
<li class="chapter" data-level="4.3" data-path="in-class-review-questions.html"><a href="in-class-review-questions.html#paired-two-sample-tests-1"><i class="fa fa-check"></i><b>4.3</b> Paired Two-Sample Tests</a></li>
<li class="chapter" data-level="4.4" data-path="in-class-review-questions.html"><a href="in-class-review-questions.html#paired-permutation-test"><i class="fa fa-check"></i><b>4.4</b> Paired Permutation Test</a></li>
<li class="chapter" data-level="4.5" data-path="in-class-review-questions.html"><a href="in-class-review-questions.html#anova-and-classic-f-test"><i class="fa fa-check"></i><b>4.5</b> ANOVA and Classic <span class="math inline">\(F\)</span>-Test</a></li>
<li class="chapter" data-level="4.6" data-path="in-class-review-questions.html"><a href="in-class-review-questions.html#kruskal-wallis-test"><i class="fa fa-check"></i><b>4.6</b> Kruskal-Wallis Test</a></li>
<li class="chapter" data-level="4.7" data-path="in-class-review-questions.html"><a href="in-class-review-questions.html#sse-from-anova"><i class="fa fa-check"></i><b>4.7</b> SSE (from ANOVA)</a></li>
<li class="chapter" data-level="4.8" data-path="in-class-review-questions.html"><a href="in-class-review-questions.html#sstr-from-anova"><i class="fa fa-check"></i><b>4.8</b> SSTr (from ANOVA)</a></li>
<li class="chapter" data-level="4.9" data-path="in-class-review-questions.html"><a href="in-class-review-questions.html#permutation-f-test-1"><i class="fa fa-check"></i><b>4.9</b> Permutation <span class="math inline">\(F\)</span>-test</a></li>
<li class="chapter" data-level="4.10" data-path="in-class-review-questions.html"><a href="in-class-review-questions.html#multiple-comparison-pairwise-t-tests"><i class="fa fa-check"></i><b>4.10</b> Multiple Comparison (Pairwise <span class="math inline">\(t\)</span>-Tests)</a></li>
</ul></li>
<li class="divider"></li>
<li>Shaandro Sarkar</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STAT 423 Review Guide</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="paired-two-sample-tests" class="section level1">
<h1><span class="header-section-number">1</span> Paired Two-Sample Tests</h1>
<p>Data for paired two-sample tests have the following properties:</p>
<ul>
<li>each subject <span class="math inline">\(i\)</span> has two observations <span class="math inline">\(X_i\)</span> and <span class="math inline">\(Y_i\)</span> to give a paired observation <span class="math inline">\((X_i, Y_i)\)</span></li>
<li><span class="math inline">\((X_1, Y_1), \dots, (X_n, Y_n)\)</span> are independent</li>
</ul>
<p>Our general strategy is to perform one-sample tests on the paired difference <span class="math inline">\(Z_i = Y_i - X_i\)</span></p>
<p>For this section, we will use the R dataset <code>sleep</code>.
In this data, each subject was given both drug 1 and drug 2,
and the change in their sleep was measured.
The column <code>group</code> indicates which drug the subject took,
and the column <code>extra</code> indicates the change in sleep.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw">data</span>(<span class="st">&quot;sleep&quot;</span>)</a>
<a class="sourceLine" id="cb1-2" title="2"></a>
<a class="sourceLine" id="cb1-3" title="3"><span class="co"># X: effect on sleep from drug 1</span></a>
<a class="sourceLine" id="cb1-4" title="4">x &lt;-<span class="st"> </span>sleep<span class="op">$</span>extra[sleep<span class="op">$</span>group <span class="op">==</span><span class="st"> </span><span class="dv">1</span>]</a>
<a class="sourceLine" id="cb1-5" title="5"></a>
<a class="sourceLine" id="cb1-6" title="6"><span class="co"># Y: effect on sleep from drug 2</span></a>
<a class="sourceLine" id="cb1-7" title="7">y &lt;-<span class="st"> </span>sleep<span class="op">$</span>extra[sleep<span class="op">$</span>group <span class="op">==</span><span class="st"> </span><span class="dv">2</span>]</a>
<a class="sourceLine" id="cb1-8" title="8"></a>
<a class="sourceLine" id="cb1-9" title="9"><span class="co"># Z: paired difference between X and Y</span></a>
<a class="sourceLine" id="cb1-10" title="10">z &lt;-<span class="st"> </span>y <span class="op">-</span><span class="st"> </span>x</a></code></pre></div>
<p>For each of these tests, we will be testing the hypotheses
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = 0\)</span> vs <span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu \neq 0\)</span>,
where <span class="math inline">\(\mu\)</span> is the mean of <span class="math inline">\(Z\)</span>.</p>
<div id="paired-t-test" class="section level2">
<h2><span class="header-section-number">1.1</span> Paired <span class="math inline">\(t\)</span>-test</h2>
<ul>
<li>Parametric test</li>
<li>One-sample <span class="math inline">\(t\)</span>-test on the mean <span class="math inline">\(\mu\)</span> of <span class="math inline">\(Z\)</span></li>
<li>Assumption: <span class="math inline">\(Z_i \overset{\mathrm{iid}} \sim N(\mu, \sigma^2)\)</span></li>
<li>Hypotheses: <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu = \mu_0\)</span> vs <span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu \neq \mu_0\)</span> (or <span class="math inline">\(&lt;\)</span>, <span class="math inline">\(&gt;\)</span>)</li>
<li>Test statistic: <span class="math display">\[T_{\mathrm{obs}} = \frac{\bar{Z} - \mu_0}{s_Z / \sqrt{n}},\]</span>
where <span class="math inline">\(\bar{Z}\)</span> and <span class="math inline">\(s_Z\)</span> are the sample mean and sample standard deviation
of <span class="math inline">\(Z\)</span></li>
<li>Null distribution: Under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(T_{\mathrm{obs}} \sim t_{n-1}\)</span></li>
</ul>
<p>There are three ways to do this test in R using the function <code>t.test</code>.</p>
<p>If the observations for group <span class="math inline">\(X\)</span> and group <span class="math inline">\(Y\)</span> are stored in separate vectors <code>x</code> and <code>y</code>,
then we use <code>t.test</code> with the argument <code>paired = TRUE</code>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1"><span class="kw">t.test</span>(x, y, <span class="dt">paired =</span> <span class="ot">TRUE</span>, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  x and y
## t = -4.0621, df = 9, p-value = 0.002833
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.4598858 -0.7001142
## sample estimates:
## mean of the differences 
##                   -1.58</code></pre>
<p>If the paired differences <span class="math inline">\(Z = Y - X\)</span> are stored in one vector
<code>z</code>, then we use a one-sample <code>t.test</code>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1"><span class="kw">t.test</span>(z, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  z
## t = 4.0621, df = 9, p-value = 0.002833
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  0.7001142 2.4598858
## sample estimates:
## mean of x 
##      1.58</code></pre>
<p>If the data is stored in one matrix or dataframe
where one column contains the observations and another column contains the groups,
we can use the following syntax.
For this data, <code>extra</code> contains the observations, and <code>group</code> indicates
which group each observation comes from.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1"><span class="kw">t.test</span>(extra <span class="op">~</span><span class="st"> </span>group, <span class="dt">paired =</span> <span class="ot">TRUE</span>, <span class="dt">data =</span> sleep, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  extra by group
## t = -4.0621, df = 9, p-value = 0.002833
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.4598858 -0.7001142
## sample estimates:
## mean of the differences 
##                   -1.58</code></pre>
<p>The result for all three values is the same:
<span class="math inline">\(p\text{-value} = 0.002833\)</span>.</p>
</div>
<div id="sign-test" class="section level2">
<h2><span class="header-section-number">1.2</span> Sign test</h2>
<ul>
<li>Also called binomial test</li>
<li>Nonparametric test on the median <span class="math inline">\(\theta\)</span> of <span class="math inline">\(Z\)</span></li>
<li>Assumption: <span class="math inline">\(Z_i\)</span> are iid</li>
<li>Hypotheses: <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\theta = \theta_0\)</span> vs <span class="math inline">\(H_a\)</span>: <span class="math inline">\(\theta \neq \theta_0\)</span> (or <span class="math inline">\(&lt;\)</span>, <span class="math inline">\(&gt;\)</span>)</li>
<li>Test statistic: <span class="math display">\[X = I\{Z_i &gt; \theta_0\},\]</span>
where <span class="math inline">\(I\{Z_i &gt; \theta_0\}\)</span> is the number of observations <span class="math inline">\(Z_i\)</span> that are greater than <span class="math inline">\(\theta_0\)</span>.</li>
<li>Null distribution: Under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(X \sim \mathrm{Binom}(n, p = 0.5)\)</span></li>
</ul>
<p>The alternative hypothesis <span class="math inline">\(H_a\)</span>: <span class="math inline">\(\theta &lt; 0\)</span>
is equivalent to <span class="math inline">\(H_a\)</span>: <span class="math inline">\(p &lt; 0.5\)</span>, where <span class="math inline">\(p = P(Z_i &gt; 0)\)</span>.
This is because, under <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\theta = 0\)</span>, the probability of <span class="math inline">\(Z_i\)</span> being less than the
median <span class="math inline">\(\theta\)</span> is 0.5.</p>
<p>The test is conducted as follows.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1"><span class="co"># calculate paired differences</span></a>
<a class="sourceLine" id="cb8-2" title="2">z &lt;-<span class="st"> </span>y <span class="op">-</span><span class="st"> </span>x</a>
<a class="sourceLine" id="cb8-3" title="3"></a>
<a class="sourceLine" id="cb8-4" title="4"><span class="co"># calculate the number of observations greater than 0</span></a>
<a class="sourceLine" id="cb8-5" title="5">X &lt;-<span class="st"> </span><span class="kw">sum</span>(z <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>)</a>
<a class="sourceLine" id="cb8-6" title="6"></a>
<a class="sourceLine" id="cb8-7" title="7"><span class="co"># calculate p-value</span></a>
<a class="sourceLine" id="cb8-8" title="8"><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">min</span>(<span class="kw">pbinom</span>(X, <span class="dt">size =</span> <span class="kw">length</span>(z), <span class="dt">prob =</span> <span class="fl">0.5</span>),</a>
<a class="sourceLine" id="cb8-9" title="9">        <span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pbinom</span>(X, <span class="dt">size =</span> <span class="kw">length</span>(z), <span class="dt">prob =</span> <span class="fl">0.5</span>))</a></code></pre></div>
<pre><code>## [1] 0.001953125</code></pre>
</div>
<div id="wilcoxon-signed-rank-test" class="section level2">
<h2><span class="header-section-number">1.3</span> Wilcoxon Signed-Rank Test</h2>
<ul>
<li>Nonparametric test on the median <span class="math inline">\(\theta\)</span> of <span class="math inline">\(Z\)</span></li>
<li>Assumptions: <span class="math inline">\(Z_i\)</span> are iid and symmetric</li>
<li>Hypotheses: <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\theta = \theta_0\)</span> vs <span class="math inline">\(H_a\)</span>: <span class="math inline">\(\theta \neq \theta_0\)</span> (or <span class="math inline">\(&lt;\)</span>, <span class="math inline">\(&gt;\)</span>)</li>
<li>Test statistic: <span class="math display">\[V = \sum_{i = 1}^n I\{Z_i &gt; \theta_0\} \mathrm{rank}(|Z_i - \theta_0|)\]</span></li>
</ul>
<p>Like with the paired <span class="math inline">\(t\)</span>-test, there are three ways to conduct the Wilcoxon test
using <code>wilcox.test</code>.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1"><span class="kw">wilcox.test</span>(x, y, <span class="dt">paired =</span> <span class="ot">TRUE</span>, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## Warning in wilcox.test.default(x, y, paired = TRUE, alternative = &quot;two.sided&quot;):
## cannot compute exact p-value with ties</code></pre>
<pre><code>## Warning in wilcox.test.default(x, y, paired = TRUE, alternative = &quot;two.sided&quot;):
## cannot compute exact p-value with zeroes</code></pre>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  x and y
## V = 0, p-value = 0.009091
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1"><span class="kw">wilcox.test</span>(z, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## Warning in wilcox.test.default(z, alternative = &quot;two.sided&quot;): cannot compute
## exact p-value with ties</code></pre>
<pre><code>## Warning in wilcox.test.default(z, alternative = &quot;two.sided&quot;): cannot compute
## exact p-value with zeroes</code></pre>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  z
## V = 45, p-value = 0.009091
## alternative hypothesis: true location is not equal to 0</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1"><span class="kw">wilcox.test</span>(extra <span class="op">~</span><span class="st"> </span>group, <span class="dt">paired =</span> <span class="ot">TRUE</span>, <span class="dt">data =</span> sleep, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## Warning in wilcox.test.default(x = c(0.7, -1.6, -0.2, -1.2, -0.1, 3.4, 3.7, :
## cannot compute exact p-value with ties</code></pre>
<pre><code>## Warning in wilcox.test.default(x = c(0.7, -1.6, -0.2, -1.2, -0.1, 3.4, 3.7, :
## cannot compute exact p-value with zeroes</code></pre>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  extra by group
## V = 0, p-value = 0.009091
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Using all three methods, <span class="math inline">\(p\text{-value} = 0.009091\)</span>.</p>
</div>
<div id="permutation-test" class="section level2">
<h2><span class="header-section-number">1.4</span> Permutation Test</h2>
<ul>
<li>Paired data <span class="math inline">\((X_i, Y_i)\)</span>, where <span class="math inline">\(X_i\)</span> and <span class="math inline">\(Y_i\)</span> are correlated</li>
<li>Assumption: <span class="math inline">\((X_1, Y_1), \dots, (X_n, Y_n)\)</span> are iid</li>
<li>For <span class="math inline">\(n\)</span> subjects, there are <span class="math inline">\(R = 2^n\)</span> equally likely permutation outcomes</li>
<li>For each possible outcome <span class="math inline">\(\ell \in \{1, \dots, R\}\)</span>, we calculate the sample mean of differences
<span class="math display">\[z_\ell = \frac{1}{n} \sum_{i=1}^n (Y_{\ell i} - X_{\ell i}),\]</span>
where <span class="math inline">\((X_{\ell i}, Y_{\ell i})\)</span> is the <span class="math inline">\(i\)</span>th observation of the <span class="math inline">\(\ell\)</span>th permutation outcome.</li>
</ul>
<p>The <span class="math inline">\(p\)</span>-value depends on the direction of <span class="math inline">\(H_a\)</span>.</p>
<table>
<thead>
<tr class="header">
<th align="left"><span class="math inline">\(H_a\)</span></th>
<th align="left"><span class="math inline">\(p\)</span>-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(\mu &gt; 0\)</span></td>
<td align="left"><span class="math inline">\(I\{z_\ell \geq \bar{Z}\} / R\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\mu &lt; 0\)</span></td>
<td align="left"><span class="math inline">\(I\{z_\ell \leq \bar{Z}\} / R\)</span></td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(\mu \neq 0\)</span></td>
<td align="left"><span class="math inline">\(I\{|z_\ell| \geq |\bar{Z}|\} / R\)</span></td>
</tr>
</tbody>
</table>
<div id="exact-permutation-test" class="section level3">
<h3><span class="header-section-number">1.4.1</span> Exact permutation test</h3>
<p>The exact permutation test for <span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu \neq 0\)</span> is performed as follows.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" title="1"><span class="co"># paired differences</span></a>
<a class="sourceLine" id="cb22-2" title="2">z &lt;-<span class="st"> </span>y <span class="op">-</span><span class="st"> </span>x</a>
<a class="sourceLine" id="cb22-3" title="3"><span class="co"># sample size</span></a>
<a class="sourceLine" id="cb22-4" title="4">n &lt;-<span class="st"> </span><span class="kw">length</span>(z)</a>
<a class="sourceLine" id="cb22-5" title="5"></a>
<a class="sourceLine" id="cb22-6" title="6"><span class="co"># create permutation matrix</span></a>
<a class="sourceLine" id="cb22-7" title="7">lists &lt;-<span class="st"> </span><span class="kw">split</span>(<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>), n, <span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>), <span class="dv">1</span><span class="op">:</span>n)</a>
<a class="sourceLine" id="cb22-8" title="8">all.outcomes &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(<span class="kw">expand.grid</span>(lists))</a>
<a class="sourceLine" id="cb22-9" title="9"></a>
<a class="sourceLine" id="cb22-10" title="10"><span class="co"># observed test statistic</span></a>
<a class="sourceLine" id="cb22-11" title="11">zbar &lt;-<span class="st"> </span><span class="kw">mean</span>(z)</a>
<a class="sourceLine" id="cb22-12" title="12"></a>
<a class="sourceLine" id="cb22-13" title="13"><span class="co"># test statistic for permutation samples</span></a>
<a class="sourceLine" id="cb22-14" title="14">zl &lt;-<span class="st"> </span><span class="kw">apply</span>(all.outcomes, <span class="dv">1</span>, <span class="cf">function</span>(u) <span class="kw">mean</span>(u<span class="op">*</span><span class="kw">abs</span>(z)))</a>
<a class="sourceLine" id="cb22-15" title="15"></a>
<a class="sourceLine" id="cb22-16" title="16"><span class="co"># p-value</span></a>
<a class="sourceLine" id="cb22-17" title="17"><span class="kw">mean</span>(<span class="kw">abs</span>(zl) <span class="op">&gt;=</span><span class="st"> </span><span class="kw">abs</span>(zbar))</a></code></pre></div>
<pre><code>## [1] 0.00390625</code></pre>
<p>In this example, we used the sample mean as our test statistic,
but the choice of test statistic for the permutation test is flexible.</p>
</div>
<div id="large-sample-approximation-for-permutation-test" class="section level3">
<h3><span class="header-section-number">1.4.2</span> Large-sample approximation for permutation test</h3>
<p>Instead of using all <span class="math inline">\(R = 2^n\)</span> possible permutation outcomes,
we can randomly select <span class="math inline">\(R\)</span> permutation outcomes and calculate the approximate <span class="math inline">\(p\)</span>-value.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1">R &lt;-<span class="st"> </span><span class="dv">1000</span></a>
<a class="sourceLine" id="cb24-2" title="2">z &lt;-<span class="st"> </span>y <span class="op">-</span><span class="st"> </span>x</a>
<a class="sourceLine" id="cb24-3" title="3">n &lt;-<span class="st"> </span><span class="kw">length</span>(z)</a>
<a class="sourceLine" id="cb24-4" title="4"></a>
<a class="sourceLine" id="cb24-5" title="5"><span class="co"># generate permutation matrix</span></a>
<a class="sourceLine" id="cb24-6" title="6">outcomes &lt;-<span class="st"> </span><span class="kw">replicate</span>(R, <span class="kw">sample</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>), n, <span class="dt">replace =</span> <span class="ot">TRUE</span>))</a>
<a class="sourceLine" id="cb24-7" title="7"></a>
<a class="sourceLine" id="cb24-8" title="8"><span class="co"># observed test statistic</span></a>
<a class="sourceLine" id="cb24-9" title="9">zbar &lt;-<span class="st"> </span><span class="kw">mean</span>(z)</a>
<a class="sourceLine" id="cb24-10" title="10"></a>
<a class="sourceLine" id="cb24-11" title="11"><span class="co"># test statistic for permutation samples</span></a>
<a class="sourceLine" id="cb24-12" title="12">zl &lt;-<span class="st"> </span><span class="kw">apply</span>(outcomes, <span class="dv">2</span>, <span class="cf">function</span>(u) <span class="kw">mean</span>(u<span class="op">*</span><span class="kw">abs</span>(z)))</a>
<a class="sourceLine" id="cb24-13" title="13"></a>
<a class="sourceLine" id="cb24-14" title="14"><span class="co"># p-value</span></a>
<a class="sourceLine" id="cb24-15" title="15"><span class="kw">mean</span>(<span class="kw">abs</span>(zl) <span class="op">&gt;=</span><span class="st"> </span><span class="kw">abs</span>(zbar))</a></code></pre></div>
<pre><code>## [1] 0.004</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="independent-two-sample-tests.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/shaandro/stat-423/edit/main/paired.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
